### ISSUE TITLE
Ordenar topics por titulo y ocultar filtros/orders

### ISSUE THREAD

**Issue by mjlescano** [DemocraciaEnRed/plan32#10]
[`/lib/topic-filter/topic-filter.js`](https://github.com/DemocraciaEnRed/plan32/blob/master/lib/topic-filter/topic-filter.js#L17-L18) should only sort by title.
- [x] add `title` filter to [`lib/topic-filter/sorts.js`](https://github.com/DemocraciaEnRed/plan32/blob/master/lib/topic-filter/sorts.js#L23)
- [ ] default sort on [`/lib/topic-filter/topic-filter.js`](https://github.com/DemocraciaEnRed/plan32/blob/master/lib/topic-filter/topic-filter.js#L17-L18) should be by `title``
- [ ] remove filtering options on sidebar

**Comment by franciclo** [comment]
titulo en español, content in english
Los títulos de los topics están numerados, para filtrar alfabéticamente habría que sacarles el numero
