### ISSUE TITLE
Cambiar texto de login por "Ingresar"

### ISSUE THREAD

**Issue by mjlescano** [DemocraciaEnRed/plan32#19]
Sin el "a democracyos":

<img width="349" alt="screen shot 2016-06-30 at 21 34 01" src="https://cloud.githubusercontent.com/assets/558901/16508555/6bcf58b8-3f0a-11e6-8026-20b7a18822dd.png">

**Comment by franciclo** [comment]
ver PR de DemocracyOS #1256
