### ISSUE TITLE
Agregar fecha a cards de noticias

### ISSUE THREAD

**Issue by juanpernu** [DemocraciaEnRed/plan32#27]

**Comment by juanpernu** [comment]
![image](https://cloud.githubusercontent.com/assets/4269424/16567611/17363d90-41f7-11e6-9d53-2662a222b283.png)

**Comment by juanpernu** [comment]
![image](https://cloud.githubusercontent.com/assets/4269424/16567690/bf45f746-41f7-11e6-8931-7707c308db2b.png)

**Comment by franciclo** [comment]
Los colores en hexagesimal, son código, pasalas en texto la proxima
