### ISSUE TITLE
Nuevo diseño de landing de foros

### ISSUE THREAD

**Issue by franciclo** [DemocraciaEnRed/plan32#6]
![landing 2](https://cloud.githubusercontent.com/assets/558901/16562872/66684b14-41d5-11e6-8319-89075741293e.jpg)

**Comment by mjlescano** [comment]
Pendientes:
- [ ] mostrar el `forum.summary` debajo del titulo, si lo tiene
- [ ] mostrar el `forum.extra.youtubeVideo` debajo del summary, si lo tiene
- [ ] actualizar summaries en la DB de producción
- [ ] actualizar videos de youtube en la DB de producción

Datos de la DB:

### Un mejor Congreso (/funcionamiento-del-congreso)

**Video:** `https://youtu.be/Yhj10ur7Pls`
**Summary:**

```
Queremos un Congreso que nos represente mejor, que escuche las demandas ciudadanas, que considere el impacto de sus decisiones y que mejore sus estándares éticos.  
```

### Un mejor Poder Judicial (/sistema-de-justicia)

**Video:** `https://youtu.be/OWemyDZGjUM`
**Summary:**

```
Queremos un Poder Judicial que funcione mejor, elevar la calidad de nuestros jueces y que se implementen las grandes reformas que se necesitan para reducir la corrupción y garantizar su eficiencia. 
```

### Una mejor Administración Pública (/administracion-publica)

**Video:** `https://youtu.be/XLTeg2gCx-g`
**Summary:**

```
Queremos una Administración Pública con mejores niveles de transparencia, que sirva a los ciudadanos y que fomente la participación de los administrados.
```

### Un mejor sistema electoral (/proceso-de-eleccion)

**Video:** `https://youtu.be/xsnnsED1e1k`
**Summary:**

```
Queremos mejores reglas electorales, mejores candidatos, partidos políticos fuertes que expresen las demandas ciudadanas y que rindan cuentas a las autoridades.
```
